
FROM maven:3.9.6-eclipse-temurin-21 AS builder

WORKDIR /app

COPY file-service/pom.xml ./file-service/

WORKDIR /app/file-service
RUN mvn dependency:go-offline

COPY file-service/src ./src

RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=builder /app/file-service/target/*.jar app.jar
EXPOSE 9091
CMD ["java", "-jar", "app.jar"]